substitutions:
  _WORKING_DIR: .
  _HELM_VERSION: v2.11.0
  _GATE_BASE_URL: ''
  _UI_BASE_URL: ''
  _OAUTH2_ENABLED: 'false'
  _PUBSUB_ENABLED: 'false'
  _GATE_X509_ENABLED: 'false'
  _PUBSUB_SUBSCRIPTION_NAME: 'spin-pipeline-trigger'
  _SPINNAKER_GCP_SA_KEY_JSON_NAME: 'spinnaker-gcs-access-key.json'
  _OAUTH2_JSON_NAME: 'spinnaker-oauth-client.json'
steps:
- name: asia.gcr.io/$PROJECT_ID/cloud-builders-community-helm:${_HELM_VERSION}
  dir: ${_WORKING_DIR}
  args:
  - 'bash'
  - '-c'
  - |
    set +x
    set -eo pipefail

    OPTIONAL_PARAMS=""

    [[ "${_OAUTH2_ENABLED}" == "true" ]] && \
      OPTIONAL_PARAMS="$$OPTIONAL_PARAMS --oauth2-json-name ${_OAUTH2_JSON_NAME} --gate-base-url ${_GATE_BASE_URL}"

    [[ ! -z "${_GATE_BASE_URL}" ]] && \
      OPTIONAL_PARAMS="$$OPTIONAL_PARAMS --gate-base-url ${_GATE_BASE_URL}"

    [[ ! -z "${_UI_BASE_URL}" ]] && \
      OPTIONAL_PARAMS="$$OPTIONAL_PARAMS --ui-base-url ${_UI_BASE_URL}"

    [[ "${_PUBSUB_ENABLED}" == "true" ]] && \
      OPTIONAL_PARAMS="$$OPTIONAL_PARAMS --pubsub-subscription ${_PUBSUB_SUBSCRIPTION_NAME}"

    [[ "${_GATE_X509_ENABLED}" == "true" ]] && \
      OPTIONAL_PARAMS="$$OPTIONAL_PARAMS --enable-gate-x509"


    ./install-spinnaker.sh \
        --project ${_CD_PROJECT_ID} \
        --helm-release-name ${_HELM_RELEASE_NAME} \
        --spinnaker-gcp-sa-key-json-name ${_SPINNAKER_GCP_SA_KEY_JSON_NAME} \
        $$OPTIONAL_PARAMS
  env:
  - 'GCLOUD_PROJECT=${_CD_PROJECT_ID}'
  - 'CLOUDSDK_COMPUTE_REGION=${_CLOUDSDK_COMPUTE_REGION}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}'
  - 'TILLERLESS=true'
timeout: 1800s
tags: ['spinnaker']
