substitutions:
  _WORKING_DIR: .
  _HELM_RELEASE_NAME: ea-cd-spin
  _HELM_VERSION: v2.11.0
  _CD_PROJECT_ID: cd-pipeline-2
  _CLOUDSDK_CONTAINER_CLUSTER: ea-cd-gke
  _CLOUDSDK_COMPUTE_REGION: australia-southeast1
  _OAUTH2_ENABLED: 'true'
  _PUBSUB_ENABLED: 'true'
  _PUBSUB_SUBSCRIPTION_NAME: 'spin-pipeline-trigger'
  _GCS_SA_KEY_JSON_NAME: 'spinnaker-gcs-sa-key.json'
  _PUBSUB_SA_KEY_JSON_NAME: 'spinnaker-pubsub-sa-key.json'
steps:
- name: asia.gcr.io/$PROJECT_ID/cloud-builders-community-helm:${_HELM_VERSION}
  dir: ${_WORKING_DIR}
  args:
  - 'bash'
  - '-c'
  - |
    set +x
    set -eo pipefail

    OPTIONAL_PARAMS=""

    [[ "${_OAUTH2_ENABLED}" == "true" ]] && \
      OPTIONAL_PARAMS="$$OPTIONAL_PARAMS --oauth2-client-id $$OAUTH2_CLIENT_ID --oauth2-client-secret $$OAUTH2_CLIENT_SECRET"

    [[ "${_PUBSUB_ENABLED}" == "true" ]] && \
      OPTIONAL_PARAMS="$$OPTIONAL_PARAMS --pubsub-subscription ${_PUBSUB_SUBSCRIPTION_NAME} --pubsub-sa-key-json-name ${_PUBSUB_SA_KEY_JSON_NAME}"

    ./install-spinnaker.sh \
        --project ${_CD_PROJECT_ID} \
        --helm-release-name ${_HELM_RELEASE_NAME} \
        --gcs-sa-key-json-name ${_GCS_SA_KEY_JSON_NAME} \
        $$OPTIONAL_PARAMS
  env:
  - 'GCLOUD_PROJECT=${_CD_PROJECT_ID}'
  - 'CLOUDSDK_COMPUTE_REGION=${_CLOUDSDK_COMPUTE_REGION}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}'
  - 'OAUTH2_CLIENT_ID=${_OAUTH2_CLIENT_ID}'
  - 'OAUTH2_CLIENT_SECRET=${_OAUTH2_CLIENT_SECRET}'
  - 'TILLERLESS=true'
timeout: 1800s
tags: ['spinnaker']
