spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: spin-deck
          servicePort: 9000
      - path: /auth/*
        backend:
          serviceName: spin-gate
          servicePort: 8084
      - path: /gate/*
        backend:
          serviceName: spin-gate
          servicePort: 8084
