spec:
  rules:
  - host: spinnaker.ea.paas.test
    http:
      paths:
      - path: /
        backend:
          serviceName: spin-deck
          servicePort: 9000
      - path: /*
        backend:
          serviceName: spin-deck
          servicePort: 9000
      - path: /auth/*
        backend:
          serviceName: spin-gate
          servicePort: 8084
