substitutions:
  _WORKING_DIR: install-spinnaker
  _CD_PROJECT_ID: ea-paas
  _CLOUDSDK_CONTAINER_CLUSTER: ea-cd-gke
  _CLOUDSDK_COMPUTE_REGION: australia-southeast1
steps:
- name: asia.gcr.io/$PROJECT_ID/helm
  dir: ${_WORKING_DIR}
  args:
  - 'bash'
  - '-c'
  - |
    set -x
    helm --debug list -a
    helm --debug status ea-cd-spin 
    helm --debug delete --purge ea-cd-spin --timeout 1200 --wait 
  env:
  - 'GCLOUD_PROJECT=$_CD_PROJECT_ID'
  - 'CLOUDSDK_COMPUTE_REGION=$_CLOUDSDK_COMPUTE_REGION'
  - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLOUDSDK_CONTAINER_CLUSTER'
  - 'TILLERLESS=true'
timeout: 1800s
tags: ['spinnaker']
