halyard:
  spinnakerVersion: 1.10.5
  image:
    repository: gcr.io/spinnaker-marketplace/halyard
    tag: 1.12.0
  # Provide a config map with Hal commands that will be run the core config (storage)
  # The config map should contain a script in the config.sh key
  additionalScripts:
    create: true
    data: {}
  additionalSecrets:
    create: true
    data: {}
  additionalConfigMaps:
    create: true
    data: {}

# Define which registries and repositories you want available in your
# Spinnaker pipeline definitions
# For more info visit:
#   https://www.spinnaker.io/setup/providers/docker-registry/

#Configure your Docker registries here
dockerRegistries:
- name: asia-gcr
  address: https://asia.gcr.io
  username: _json_key
  password: ''
  email: 1234@5678.com
#  repositories:
#  - ea_paas

# If you don't want to put your passwords into a values file
# you can use a pre-created secret instead of putting passwords
# (specify secret name in below `dockerRegistryAccountSecret`)
# per account above with data in the format:
# <name>: <password>

#dockerRegistryAccountSecret: myregistry-secrets

kubeConfig:
  # Use this when you want to register arbitrary clusters with Spinnaker
  # Upload your ~/kube/.config to a secret
  enabled: false
#  secretName: my-kubeconfig
#  secretKey: config
  # List of contexts from the kubeconfig to make available to Spinnaker
  contexts:
  - spinnaker
  deploymentContext: spinnaker

# Change this if youd like to expose Spinnaker outside the cluster
ingress:
  enabled: false
  host: ""
  #annotations:
  #  ingress.kubernetes.io/ssl-redirect: 'true'
  #  kubernetes.io/ingress.class: nginx
  #  kubernetes.io/tls-acme: 'true'
  # tls:
  #  - secretName: -tls
  #    hosts:
  #      - domain.com

# spinnakerFeatureFlags is a list of Spinnaker feature flags to enable
# Ref: https://www.spinnaker.io/reference/halyard/commands/#hal-config-features-edit
# spinnakerFeatureFlags:
#   - artifacts
#   - pipeline-templates
spinnakerFeatureFlags:
- artifacts
- jobs
- pipeline-templates

# Node labels for pod assignment
# Ref: https://kubernetes.io/docs/user-guide/node-selection/
# nodeSelector to provide to each of the Spinnaker components
nodeSelector: {}

# Redis password to use for the in-cluster redis service
# Redis is not exposed publically
redis:
  password: password
  nodeSelector: {}
  cluster:
    enabled: true
  # Uncomment if you don't want to create a PVC for redis
  master:
    persistence:
      enabled: true

# Minio access/secret keys for the in-cluster S3 usage
# Minio is not exposed publically
minio:
  enabled: false

gcs:
  enabled: true
  project: ""
  bucket: ""
  jsonKey: ''

s3:
  enabled: false

rbac:
  # Specifies whether RBAC resources should be created
  create: true

serviceAccount:
  # Specifies whether a ServiceAccount should be created
  create: true
  # The name of the ServiceAccounts to use.
  # If left blank it is auto-generated from the fullname of the release
  halyardName: ex-halyard
  spinnakerName: ex-spinnaker
