substitutions:
  _WORKING_DIR: .
  _EX_SPIN_CLI_VERSION: v0.0.1
  _CD_PROJECT_ID: diwali-16838
  _CLOUDSDK_CONTAINER_CLUSTER: diwali-16838-gke
  _CLOUDSDK_COMPUTE_REGION: asia-southeast1
  _X509_CERT: gs://diwali-16838-app-config/roer.crt
  _X509_KEY: gs://diwali-16838-app-config/roer.key
steps:
- name: asia.gcr.io/$PROJECT_ID/cloud-builders-ex-spin-cli:${_EX_SPIN_CLI_VERSION}
  dir: ${_WORKING_DIR}
  args:
  - --x509-cert
  - ${_X509_CERT}
  - --x509-key
  - ${_X509_KEY}
  - --kubectl-proxy
  - --pipeline-template
  - deploy-manifest.yml
  env:
  - 'GCLOUD_PROJECT=${_CD_PROJECT_ID}'
  - 'CLOUDSDK_COMPUTE_REGION=${_CLOUDSDK_COMPUTE_REGION}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}'
timeout: 900s
