substitutions:
  _WORKING_DIR: .
  _JENKINS_SLAVE_VERSION: '3.27-1'
steps:
- name: 'gcr.io/cloud-builders/docker'
  dir: ${_WORKING_DIR}
  args: [
    'build',
    '--build-arg',
    'BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`',
    '--build-arg',
    'COMMIT_SHA=$COMMIT_SHA',
    '--build-arg',
    'JENKINS_SLAVE_VERSION=${_JENKINS_SLAVE_VERSION}',
    '--tag=asia.gcr.io/$PROJECT_ID/jenkins-jnlp-slave:${_JENKINS_SLAVE_VERSION}',
    '.'
  ]
images: ['asia.gcr.io/$PROJECT_ID/jenkins-jnlp-slave:${_JENKINS_SLAVE_VERSION}']
tags:
  - "jenkins"
  - "jnlp-slave"
