apiVersion: v1
kind: Service
metadata:
  name: hello-app
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    app: hello-app
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 0.0.0.0/32
  selector:
    app: hello-app
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
