Master:
  ContainerEnv:
    - name: JENKINS_HOSTNAME
      value: "http://jenkins.manikann.com:8080"
    - name: GOOGLE_OAUTH_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: google-oauth
          key: client-id
    - name: GOOGLE_OAUTH_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: google-oauth
          key: client-secret
  ServiceType: ClusterIP
  ServiceAnnotations:
    cloud.google.com/load-balancer-type: Internal
  JavaOpts: >
    -Xms512m -Xmx2g
  InstallPlugins:
rbac:
  install: true
  serviceAccountName: jenkins
