substitutions:
  _WORKING_DIR: .
  _VERSION: v0.0.2
steps:
- name: 'gcr.io/cloud-builders/docker'
  dir: ${_WORKING_DIR}
  args: [
    'build',
    '--build-arg',
    'BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`',
    '--build-arg',
    'COMMIT_SHA=$COMMIT_SHA',
    '--build-arg',
    'PROJECT_ID=${PROJECT_ID}',
    '--tag=asia.gcr.io/$PROJECT_ID/configure-spin-k8s-account:${_VERSION}',
    '--tag=asia.gcr.io/$PROJECT_ID/configure-spin-k8s-account:latest',
    '.'
  ]

images: ['asia.gcr.io/$PROJECT_ID/configure-spin-k8s-account:${_VERSION}',
         'asia.gcr.io/$PROJECT_ID/configure-spin-k8s-account:latest']
tags:
  - "roer"
  - "helm"
  - "tillerless"
