# Common settings.
global:
  # Include the crd definition when generating the template.
  # For 'helm template' and helm install > 2.10 it should be true.
  # For helm < 2.9, crds must be installed ahead of time with
  # 'kubectl apply -f install/kubernetes/helm/istio/templates/crds.yaml
  # and this options must be set off.
  crds: true

  # Omit the istio-sidecar-injector configmap when generate a
  # standalone gateway. Gateways may be created in namespaces other
  # than `istio-system` and we don't want to re-create the injector
  # configmap in those.
  omitSidecarInjectorConfigMap: true

  # Istio control plane namespace: This specifies where the Istio control
  # plane was installed earlier.  Modify this if you installed the control
  # plane in a different namespace than istio-system.
  istioNamespace: istio-system

  proxy:
    # Sets the destination Statsd in envoy (the value of the "--statsdUdpAddress" proxy argument
    # would be <host>:<port>).
    # Disabled by default.
    # The istio-statsd-prom-bridge is deprecated and should not be used moving forward.
    envoyStatsd:
      # If enabled is set to true, host and port must also be provided. Istio no longer provides a statsd collector.
      enabled: false
      host: # example: statsd-svc
      port: # example: 9125


#
# Gateways Configuration
# By default (if enabled) a pair of Ingress and Egress Gateways will be created for the mesh.
# You can add more gateways in addition to the defaults but make sure those are uniquely named
# and that NodePorts are not conflicting.
# Disable specifc gateway by setting the `enabled` to false.
#
gateways:
  enabled: true

  ex-gateway:
    enabled: true
    labels:
      app: ex-gateway
    replicaCount: 1
    autoscaleMin: 1
    autoscaleMax: 5
    resources: {}
      # limits:
      #  cpu: 100m
      #  memory: 128Mi
      #requests:
      #  cpu: 1800m
      #  memory: 256Mi
    cpu:
      targetAverageUtilization: 80
    loadBalancerIP: ""
    serviceAnnotations:
      cloud.google.com/load-balancer-type: "Internal"
    type: LoadBalancer
    externalTrafficPolicy: Local
    ports:
      ## You can add custom gateway ports
    - port: 443
      name: https
    - port: 31400
      name: tcp
    secretVolumes:
    - name: ex-gw-certs
      secretName: istio-ex-gw-certs
      mountPath: /etc/istio/ex-gw-certs
    - name: ex-gw-ca-certs
      secretName: istio-ex-gw-ca-certs
      mountPath: /etc/istio/ex-gw-ca-certs

# all other components are disabled except the gateways
ingress:
  enabled: false

security:
  enabled: true

sidecarInjectorWebhook:
  enabled: false

galley:
  enabled: false

mixer:
  enabled: false

pilot:
  enabled: true

grafana:
  enabled: false

prometheus:
  enabled: false

servicegraph:
  enabled: false

tracing:
  enabled: false

kiali:
  enabled: false

certmanager:
  enabled: false
