substitutions:
  _WORKING_DIR: .
  _SPIN_CLI_VERSION: v0.0.1
  _CLOUDSDK_COMPUTE_REGION: asia-southeast1
  _CD_PROJECT_ID: ex-services-pp-18655
  _CD_CLUSTER: ex-services-pp-18655-gke
  _APP_PROJECT_ID: app-project-002
  _APP_CLUSTER: ea-app-gke
  _X509_CERT: gs://ex-services-pp-18655-app-config/roer.crt
  _X509_KEY: gs://ex-services-pp-18655-app-config/roer.key
  _SPIN_KUBECONFIG: gs://ex-services-pp-18655-app-config/app-register.kubeconfig
  _MANIFEST_BUCKET_NAME: app-project-002-spinnaker-artifacts
  _SPIN_TOPIC_URI: projects/ex-services-pp-18655/topics/spin-pipeline
steps:
- name: asia.gcr.io/$PROJECT_ID/cloud-builders-spin-cli:${_SPIN_CLI_VERSION}
  dir: ${_WORKING_DIR}
  args:
  - '--spin-kubeconfig'
  - ${_SPIN_KUBECONFIG}
  - '--sa-name'
  - ex-spin-sa
  - '--sa-namespace'
  - default
  - '--manifest-bucket'
  - ${_MANIFEST_BUCKET_NAME}
  - '--spin-topic'
  - ${_SPIN_TOPIC_URI}
  env:
  - 'GCLOUD_PROJECT=${_APP_PROJECT_ID}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_APP_CLUSTER}'
  - 'CLOUDSDK_COMPUTE_REGION=${_CLOUDSDK_COMPUTE_REGION}'

- name: asia.gcr.io/$PROJECT_ID/cloud-builders-spin-cli:${_SPIN_CLI_VERSION}
  dir: ${_WORKING_DIR}
  args:
  - '--x509-cert'
  - ${_X509_CERT}
  - '--x509-key'
  - ${_X509_KEY}
  - '--template-config'
  - deploy-manifest-config.yml
  - '--kubectl-proxy'
  env:
  - 'GCLOUD_PROJECT=${_CD_PROJECT_ID}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CD_CLUSTER}'
  - 'CLOUDSDK_COMPUTE_REGION=${_CLOUDSDK_COMPUTE_REGION}'
timeout: 900s
