substitutions:
  _VERSION: v0.0.2
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '--tag=asia.gcr.io/$PROJECT_ID/hello-app:${_VERSION}',
    '.'
  ]
images: ['asia.gcr.io/$PROJECT_ID/hello-app:${_VERSION}']
