schema: "1"
pipeline:
  application: samplesb
  name: Deploy to Staging
  template:
    source: spinnaker://deploy-manifest
  variables:
    manifest:
      gcs_url: gs://app-project-002-spinnaker-artifacts/manifests/deploy.yml
    image:
      server: asia.gcr.io
      org: ci-project-002
      name: sample-sb
    cluster:
      namespace: default
      account: app-project-002-ea-app-gke
configuration:
  inherit:
  - concurrentExecutions
  - expectedArtifacts
  - parameters
  - triggers
