substitutions:
    _WORKING_DIR: helm-charts/spinnaker
    _CD_PROJECT_ID: ea-paas
    _CLOUDSDK_CONTAINER_CLUSTER: ea-cd-gke
    _CLOUDSDK_COMPUTE_REGION: australia-southeast1
steps:
- name: gcr.io/cloud-builders/gcloud
  dir: ${_WORKING_DIR}
  entrypoint: bash
  args:
    - '-c'
    - |
      set -xeo pipefail
      gsutil cp gs://${_CD_PROJECT_ID}-halyard-config/spinnaker-gcs-access-key.json key.json
      gcloud container clusters get-credentials ${_CLOUDSDK_CONTAINER_CLUSTER} --region ${_CLOUDSDK_COMPUTE_REGION} --project ${_CD_PROJECT_ID}
      kubectl config view --flatten
      kubectl create secret generic spinnaker-service-account-key --from-file key.json --dry-run -o yaml > secret.yaml
      kubectl apply -f secret.yaml
      cat secret.yaml
- name: gcr.io/$PROJECT_ID/helm
  dir: ${_WORKING_DIR}
  args:
      - 'helm'
      - 'upgrade'
      - '--install'
      - 'np-spin'
      - '.'
      - '--namespace'
      - 'spinnaker'
      - '--set'
      - 'project_id=$PROJECT_ID'
  env:
      - 'GCLOUD_PROJECT=$_CD_PROJECT_ID'
      - 'CLOUDSDK_COMPUTE_REGION=$_CLOUDSDK_COMPUTE_REGION'
      - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLOUDSDK_CONTAINER_CLUSTER'
      - 'TILLERLESS=true'
tags: ['spinnaker']
