apiVersion: v1
kind: Service
metadata:
  name: k8s-api-proxy
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    app: k8s-api-proxy
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
    - 192.0.2.0/24  # Special ip range, not in use. Used here to disable the coarse grained firewall automatically created. Refer https://tools.ietf.org/html/rfc3330
  selector:
    app: k8s-api-proxy
  ports:
  - port: 8118
    protocol: TCP
    targetPort: 8118
