apiVersion: v1
kind: Service
metadata:
  name: k8s-api-proxy
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    app: k8s-api-proxy
spec:
  type: LoadBalancer
  selector:
    app: k8s-api-proxy
  ports:
  - port: 8118
    protocol: TCP
    targetPort: 8118
