{{- $chart_name := .Chart.Name }}
{{- $chart_version := .Chart.Version | replace "+" "_" }}
{{- $release_name := .Release.Name }}

{{- if .Values.imageCredentials }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $release_name }}-registry"
  labels:
   chart: "{{ $chart_name }}-{{ $chart_version }}"
   release: {{ $release_name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecretJSONKey" . }}
{{- end }}
