substitutions:
  _WORKING_DIR: .
  _EX_GKE_CLUSTER: ea-cd-gke
  _EX_PROJECT_ID: cd-pipeline-1
  _REGION: australia-southeast1
  _APP_GKE_CLUSTER: ea-app-gke
  _APP_PROJECT_ID: app-service-12
  _HELM_VERSION: v2.11.0
steps:
- name: asia.gcr.io/$PROJECT_ID/cloud-builders-community-helm:${_HELM_VERSION}
  dir: ${_WORKING_DIR}
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    ./register-app.sh \
        --ex-cluster ${_EX_GKE_CLUSTER} \
        --ex-project-id ${_EX_PROJECT_ID} \
        --app-cluster ${_APP_GKE_CLUSTER} \
        --app-project-id ${_APP_PROJECT_ID} \
        --region ${_REGION}
timeout: 900s
