substitutions:
  _WORKING_DIR: .
  _EX_GKE_CLUSTER: ea-cd-gke
  _EX_PROJECT_ID: cd-pipeline-2
  _REGION: australia-southeast1
  _APP_GKE_CLUSTER: ea-app-gke
  _APP_PROJECT_ID: app-service-123
  _HELM_VERSION: v2.11.0
  _BUCKET_URL: gs://pipeline-integration-app-service-123/
  _PUBLISH_TOPIC: spin-pipeline
steps:
- name: asia.gcr.io/$PROJECT_ID/cloud-builders-community-helm:${_HELM_VERSION}
  dir: ${_WORKING_DIR}
  entrypoint: 'bash'
  args:
  - '-c'
  - |

    OPTIONAL_PARAM=""
    [[ ! -z "$_BUCKET_URL" ]] && OPTIONAL_PARAM="$$OPTIONAL_PARAM --bucket $_BUCKET_URL"
    [[ ! -z "$_PUBLISH_TOPIC" ]] && OPTIONAL_PARAM="$$OPTIONAL_PARAM --publish-topic $_PUBLISH_TOPIC"

    ./register-app.sh \
        --spin-cluster ${_EX_GKE_CLUSTER} \
        --spin-project-id ${_EX_PROJECT_ID} \
        --app-cluster ${_APP_GKE_CLUSTER} \
        --app-project-id ${_APP_PROJECT_ID} \
        --region ${_REGION} \
        $$OPTIONAL_PARAM
timeout: 900s
